### ISSUE TITLE
Linear referencing capabilities

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#100]
What are the plans for linear referencing capabilities beyond the existing routing.

For instance - I'd like to generate point X at Y distance along line Z.  Either in map units or using a measure (if the line has one).

This would be very helpful for numerous applications that currently require a ton of custom logic to create.

**Comment by eric906** [comment]
Currently, there are no plans for supporting linear referencing in Runtime, apart from using the Local Server. Using Local Server, there are a number of Linear Referencing tools that can be used in geoprocessing packages for performing local linear referencing tasks. It's a good point, though. The discussion has come up a number of times.
