### ISSUE TITLE
Updates to mobile map packages

### ISSUE THREAD

**Issue by randallsutton** [Esri/runtime-questions#102]
As I understand it a mobile map package can contain tile layers, locators, feature services, etc.

Will it be possible to sync just the deltas? For instance if the package has an update do I have to download everything again or can I get just the changes.

In addition, what if we only want to sync the feature layer and not the tile layer since it will be much larger?

Also will be it be possible to sync just the deltas for vector tile layers like we do for sync-enabled feature services?

**Comment by eric906** [comment]
In the first Quartz release, mobile map packages will probably be read-only and not sync-enabled. The plan going forward is to make them sync enabled, so we will be working toward that goal for releases coming later.
