### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by exolvi** [Esri/runtime-questions#104]
Are there any plans to support .NET Core in the future?  Any other platforms that you have plans for?

**Comment by dotMorten** [comment]
@wirebarbed What are you hoping to be able to do with .NET Core support that you can't do today? That might help me answer the question better

**Comment by exolvi** [comment]
In this case, I don't think I am missing out on functionality, but MS is moving that direction.

**Comment by dotMorten** [comment]
.NET Core is already supported in UWP. It's really just the underlying framework, so if let's say Microsoft were to move WPF on top of .NET core (they aren't), we would just get it.

We are however actively researching being able to build on top of .NET Standard 2.0 in the future.
