### ISSUE TITLE
Update Strategy

### ISSUE THREAD

**Issue by exolvi** [Esri/runtime-questions#106]
You've delivered v100.0 and we know about updates 1 and 2, which don't seem to have breaking changes.  Beyond that, can you talk about plans for releases with breaking changes vs releases that do.  How long do you believe we will be in this flavor of ArcGIS Runtime?  Can you elaborate on the version number scheme and how that looks for architectural changes?

**Comment by willcrick** [comment]
We follow semantic versioning, so minor updates (e.g. 100.1) will not include breaking changes, but may include deprecation notices. Deprecations will only be removed in a major release update (e.g. 101 or 200)
