### ISSUE TITLE
NeTCDF and HDF support 

### ISSUE THREAD

**Issue by guidway** [Esri/runtime-questions#107]
When will scientific data formats like NETCDF and HDF be supported in runtime?

**Comment by guidway** [comment]
We use NetCDF extensively in our office and it is currently supported in ArcMap/ArcObjects. We are currently using Engine which allows us to use these formats but will not be able to move to Runtime until it has this support.

**Comment by eric906** [comment]
@guidway, direct read of NetCDF is on the roadmap, but we don't know when this support will be released just yet. Today, if you are able to use the LocalServer component of Runtime, NetCDF and HDF data can be accessed and displayed in a Runtime app through a map package (MPK) loaded by LocalServer , and can be used in conversion tools through geoprocessing packages (GPKs) loaded by LocalServer. I hope this helps.
