### ISSUE TITLE
Xamarin Studio User

### ISSUE THREAD

**Issue by SamDrummond** [Esri/runtime-questions#108]
A lot of the samples and tools for the SDK appear to have been developed for Visual Studio.  I mainly develop Apps for Android and iOS primarily on my Mac.  I'm more comfortable in Xamarin Studio than Visual Studio.  I would like to know:

- How many others are mainly using Xamarin Studio rather that Visual Studio?
- What are the key things that I'm missing out on by not using Visual Studio in my case?

**Comment by mbranscomb** [comment]
@SamDrummond In terms of ArcGIS Runtime SDK for .NET, the only thing you're missing out on is some simple project templates that are included within a Visual Studio extension (.vsix) downloadable from the ArcGIS Developers site. We currently don't build an equivalent of the .vsix for Xamarin Studio or Visual Studio for Mac. The .vsix also includes a copy of all the API NuGet packages and creates a local NuGet source, so it's really for developers who need to work offline and cannot use NuGet.org, or want an easy way to download all the packages to use on an internal NuGet server for dependency management.

You should be able to work with the samples, demos, toolkit, etc in Xamarin Studio / Visual Studio for Mac in the same way you can in Visual Studio - if you're seeing any problems, please let us know.

We'd really appreciate your feedback on support for Xamarin Studio / Visual Studio for Mac, and whether you feel an extension to those IDEs that included project templates would enhance your dev experience. And is there any additional support you would like to see us include for those IDEs?
