### ISSUE TITLE
Dev sum ?'s

### ISSUE THREAD

**Issue by taarelay** [Esri/runtime-questions#109]
10.2.7 vs 100.0: [**.NET**] When holding a **LEFT mouse button** in pan lock mode mouse events are no longer sent out for mouse move events.  Is this a bug or on purpose? If on purpose what realistic reason could there be for not ‘informing’ runtime clients where the mouse is.

*NOTE: I know the mouse event is owned by the GUI and not ESRI elements.  However, since it doesn’t happen in 100.0 there has to be an underlying change that causes this.

*NOTE: I've since heard this has been moved to a higher level of the GUI, but have not yet confirmed this

Revised 2017/03/13.  It was suggested that graphics overlay interference could be causing a problem.  I've tested this without any graphics.  On further evaluation, it seems we get only 1 event sent and no further events are sent as you are moving the mouse while holding left button.
-------------------------- 

10.2.7:  KML Layers/ KML loading files.   The ESRI KML loader does not seem to recognize the **“Data”** tag form for extended data items.  Is this planned for the re-introduction of KML in 100.?  And is there any idea what release it will return.

https://developers.google.com/kml/documentation/kmlreference#extendeddata

---------------------------------------
 

Any Version: The KML loaders in the runtime(s) only load from URIs. Is there any play to allow them to load from string content representing the contents of a KML file?  This is especially problematic for us with the JavaScript libraries.  The JS libraries only load from web exposed URLs and the KML we load is neither static nor web exposed.

 
-----------------------------------------
 

100.0: When moving the mouse in the SceneView a “ViewpointChanged” event is fired.  Nothing about the camera has changed, why is this considered a ViewpointChanged event?

**Comment by taarelay** [comment]
Item #1 .NET runtime context
Item #2 filtered text.  The missing text in quote should be the 'data' tag of the extended data.  'SchemaData' tags do work.

**Comment by taarelay** [comment]
I just re-read this and realized the text for item #1 should refer to 'holding left click'.  I was trying to enter all this from a phone and phone keyboards hate me.

**Comment by mbranscomb** [comment]
RE: Events:

This was a deliberate design change - but if you want to continue receiving the events you can use the AddHandler method. For more info see https://msdn.microsoft.com/en-us/library/ms598899(v=vs.110).aspx.

**Comment by mbranscomb** [comment]
RE: KML

KML is on the roadmap for an upcoming release. We'll investigate the feedback regarding the Data tag and creating KML from a string.

**Comment by mbranscomb** [comment]
RE: ViewpointChanged:

This appears not to be reproducible on v100.0 or the latest v100.2.1. If you are still seeing an issue please let us know in Geonet: https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net.

**Comment by mbranscomb** [comment]
@taarelay I hope the 3 responses above answer your questions. If not, please don't hesitate to let us know in Geonet - https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net.
