### ISSUE TITLE
Xamarin and the Runtime

### ISSUE THREAD

**Issue by m4tnayrb** [Esri/runtime-questions#11]
Will the ArcGIS Runtime for .NET support Xamarin or will there be a unique Runtime?  Are there plans to create a Xamarin version of AppStudio?

**Comment by EuanCameron** [comment]
The decision on how to package the Xamarin SDK has not been finalized.   The two options are adding Xamarin support to the .Net SDK, or releasing a separate Xamarin SDK.   Keeping them separate has some benefits as the tool chain required is different.   However, no matter how we package the SDK, we will ensure that the runtime APIs for .Net and Xamarin are in sync to allow you to use your code in both.

There are currently no plans to have a Xamarin version of AppStudio
