### ISSUE TITLE
v100 beta1 toolkit for .net

### ISSUE THREAD

**Issue by mrickard26** [Esri/runtime-questions#110]
Is the .net v100 toolkit on github?
Samples?

**Comment by mbranscomb** [comment]
@mrickard26 Yes, we have just released a beta this week:
- Nuget: https://www.nuget.org/packages/Esri.ArcGISRuntime.Toolkit/100.0.0-beta1
- Source and Samples: https://github.com/Esri/arcgis-toolkit-dotnet/tree/v100/src

**Comment by dotMorten** [comment]
Yes!
It's currently in the v100 branch here:
      https://github.com/Esri/arcgis-toolkit-dotnet/tree/v100
It includes sample app.

We also published this on NuGet earlier this week:
     https://www.nuget.org/packages/Esri.ArcGISRuntime.Toolkit/100.0.0-beta1
