### ISSUE TITLE
Nearest feature to point in runtime

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#111]
Can we get a feature added to the Geometry Engine or AGSQuery that will return the nearest feature for a provided AGSPoint?

**Comment by willcrick** [comment]
Good suggestion, we do not have this currently.

You can achieve this yourselves by performing a query using a point and radius, and check the number of results you have. If in the first query you have some results, you can use the geometry engine to work out which is the closest. If there are no results in the first request, you can continue to re-query with a larger buffer until you find the closest result.
