### ISSUE TITLE
TakeMapOffline Task scheduled for Update 1 - which parameters will be supported

### ISSUE THREAD

**Issue by sweihs** [Esri/runtime-questions#112]
Area of interest
list of Layers to take offlien/not take offline
etc.

**Comment by eric906** [comment]
@anttikajanus , would you like to address this question?

**Comment by anttikajanus** [comment]
We shipped on-demand (ad-hoc) workflow in 100.1 release and on 100.2 we released preplanned workflow support. On-demand workflow is used in the cases where you want to specify the area to be generated and downloaded from the runtime app but this means that the services generate the offline packages when requested. On preplanned workflow, all areas are defined in advance can be downloaded to the clients when requested.

You can see the documentation for both from [create an offline map](https://developers.arcgis.com/net/latest/wpf/guide/create-an-offline-map.htm) (here is link to .net).

- We do support taking offline tile layers, vector tile layers, feature layers and feature collections that are offline enabled
- For on demand workflow you can specify following parameters
  - area of interest
  - scale range
  - inclusion of the map's basemap
  - inclusion of the feature's attachments
  - inclusion of features from editable feature layers
  - inclusion of the map's metadata
- On preplanned workflow, most of these options are defined as part of the authoring but you can decide if you want to download basemap as part of the download or not.
