### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by kissanem** [Esri/runtime-questions#116]
Please cover licensing for Arcgis runtime using the appbuilder and/or xamarin.  We have an organizational account and several edn accounts.  We want to build mobile apps for the public.

**Comment by eric906** [comment]
Thank you for the question @kissanem.

We recently released the new Developer Subscription plan that describes what options are available to you for your development work: https://developers.arcgis.com/pricing/. Notice here that you can get started developing with the ArcGIS Runtime SDKs with a no-cost dev and test subscription with the Essentials plan. This allows you to dev and test with all licensed capabilities that Runtime provides.

Scroll down to the bottom of the Developer Subscription page and you'll find a good resource that outlines in detail the ArcGIS Runtime deployment licensing: https://developers.arcgis.com/arcgis-runtime/licensing/.

If these resources are not helpful to you, please let us know within this issue and we will get answers for you right away.

**Comment by eric906** [comment]
@kissanem I also recommend these FAQs. Thanks!
https://developers.arcgis.com/terms/faq/
