### ISSUE TITLE
What are the top 5 features of Engine that will never make it to Runtime?

### ISSUE THREAD

**Issue by esride-ral** [Esri/runtime-questions#120]
- Geometric Networks?
- ...

**Comment by eric906** [comment]
Hi @esride-ral . Never say never, right? :-)
Joking aside, most all of the capabilities found in Engine will, in one way or another, and at some point, find their way into Runtime workflows. Maybe they won't be named the same. Maybe the path to get there will be different, but we believe the end results will be achievable. That is the goal. Thanks for the great question.
