### ISSUE TITLE
Military Symbology

### ISSUE THREAD

**Issue by jkane12** [Esri/runtime-questions#122]
Is there support in v100, specifically .NET, to create/edit Military Symbology single and multipoint?  If so are there any samples?

**Comment by mbranscomb** [comment]
@jkane12 It looks like we don't currently have samples for military symbology in .NET - sorry - we'll prioritize that in our samples work and try to take a look in the next sprint.

The samples are likely to be similar to those already available for Qt and Java:
https://github.com/Esri/arcgis-runtime-samples-qt/tree/master/ArcGISRuntimeSDKQt_QMLSamples/DisplayInformation/GraphicsOverlay_DictionaryRenderer
https://github.com/Esri/arcgis-runtime-samples-java/tree/master/src/main/java/com/esri/samples/displayinformation/dictionary_renderer_graphics_overlay

**Comment by mbranscomb** [comment]
@jkane12 Can you provide more information on the workflow you would like to build for creating/editing Military Symbology?

**Comment by jkane12** [comment]
Currently we have a third party library for 2525b that we use.  It handles incoming vmf messages over the network and returns the correct symbol as a png that we can add to our map.  Also, it allows the user to create/edit symbols, single/multipoint from scratch for mission planning.  However, it is only ver. b and we are looking for the something to provide the current spec 2525D.

**Comment by jkane12** [comment]
Also, when the user is creating the symbols, there is some guidance about what the symbol requirements are as far as control points.  So if it was a multi point it would be able to tell the user that this symbol requires 3 or more points..  It doesn't look like the esri style file has that kind of per symbol information available to the user.

**Comment by jkane12** [comment]
Thanks for the links, got the .net version running straight away from the java example.  Doesn't appear to render in scene view only map view, correct?

**Comment by jkane12** [comment]
guess we are trying to create this in runtime.. [http://solutions.arcgis.com/defense/help/military-overlay/workflows/create-military-symbols/](http://solutions.arcgis.com/defense/help/military-overlay/workflows/create-military-symbols/)

**Comment by eric906** [comment]
Really helpful info, @jkane12 . Thanks

**Comment by jkane12** [comment]
Actually looking closer at the .style file, there might be everything needed in there.  Now I just have to figure out how the searching works.

**Comment by Sansun** [comment]
Hey I am new to ArcGis Android runtime and trying to create my second app using the display-device-locations app and I am getting an error importing this package 
import com.esri.arcgisruntime.sample.displaydevicelocation.R;

I am using arcgis-runtime-sdk-android-100.1.0

**Comment by eric906** [comment]
@shellygill @mbcoder

**Comment by shellygill** [comment]
Hi @Sansun - it's fairly common in Android to see errors like "cannot resolve symbol `R`" - you should not need to explicitly import the resources namespace for your module in Android, but sometimes Android Studio does end up with temporary errors like this. Normally they are solved by cleaning your project and rebuilding, or sometimes by updating your Android SDK. If you continue to have problems, I'd recommend posting on the GeoNet community (https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android), or as this is an Android Framework issue, try looking on [Stackoverflow](https://stackoverflow.com/search?q=android+import+R).
