### ISSUE TITLE
Best SQLLite viewer

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#124]
What SQLite viewer have you found that works well with the mobile GDB?

**Comment by mikedorais** [comment]
SQL Spy
Extension of FireFox
Commandline on Mac

**Comment by eric906** [comment]
@mikedorais , Thanks for the question. A good one.
You've listed the most recommended, but there are lots out there. From what I know, including use in my own work, many of us at Esri use [SQL Spy](https://sqlspy.codeplex.com/). However, there may be better ones out there!
