### ISSUE TITLE
Geodatabase functionality in Runtime vs. Pro Geodatabase API functionality

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#126]
Just saw session on Pro Geodatabase API.
Compare contrast geodatabase type functionality between that API aind Runtime SDK.

**Comment by mikedorais** [comment]
Answer heard in session:
* Biggest difference Pro suppports the Pro Enterprise Information model
* Runtime web information model.
* More DDL in Pro.  Content Creation as well as use.
* RT: Create content in terms of features, but not schema.
* RT Keep it simple
* Did a design exercise to rethink so that the APIs would not be drastically different.

**Comment by eric906** [comment]
@mikedorais Was this question answered for you? Thanks!
