### ISSUE TITLE
Possible update to 10.2.5 for token referrer bug

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#127]
Have been told that this was fixed in v100
https://geonet.esri.com/thread/169885

Any way we can get a fix out for 10.2.5?

**Comment by dg0yal** [comment]
Sorry, no plans to patch 10.2.x
It's worth upgrading to 100.x. Lots of new capabilities - vector tiles, 3d scenes, local rasters, mobile map packages,.....
