### ISSUE TITLE
Time based layers support

### ISSUE THREAD

**Issue by guidway** [Esri/runtime-questions#130]
Will time based layers be supported in Update 2? If so, will it be across all platforms or only selected? If not, what time frame is it expected to be added in?

**Comment by eric906** [comment]
Yes, Time-Aware layers are planned for Update 2. The support will be across all Runtime APIs.

**Comment by guidway** [comment]
One other related question... what Layer Types are you planning to support having time? 

A suggestion would be to allow Feature, Raster, and Graphic Layers (if possible) to have time.
