### ISSUE TITLE
Directly create runtime geodatabases and feature classes

### ISSUE THREAD

**Issue by guidway** [Esri/runtime-questions#133]
In ArcObjects you could create a file GDB and feature classes directly in code. Is this possible in Runtime for .geodatabase fIles and feature classes or if not are there any plans to provide this capability?

**Comment by eric906** [comment]
Thanks for this, Wayne. 

At the present time, there are no plans to enhance the Runtime API to directly create feature classes straight away from a Runtime app. You correctly identified this as a capability gap between Engine/ArcObjects and Runtime. We are looking at alternative dev patters for doing what's needed here. You can look at FeatureCollectionTable for a start. You can create a schema for this, and persist FeatureCollections as JSON. Or, you could use Local Server and GP to take FeatureSets and pass them to a GP tool that can flush those features to a shapefile or KML file, possibly.

**Comment by eric906** [comment]
@guidway , Please feel free to use this issue for more dialog on this topic. Thanks.
