### ISSUE TITLE
Custom orientation/units on scalebar

### ISSUE THREAD

**Issue by guidway** [Esri/runtime-questions#135]
In the Runtime road ahead session I remember hearing something about a scalebar, but was late and didn't catch all of it. Does this scalebar support both vertical and horizontal orientation?

Also can you define custom scale units  (i.e. our customer requires kiloyards instead of yards)? 

Thanks

**Comment by rolson** [comment]
There was a scalebar demo for the toolkit components. As far as the iOS scalebar, you can apply a `CGAffineTransform` to the view to turn it vertical. Also when the toolkits are shipped, the source will be available so you can modify it in any way you want, including changing the units. The units in the demo that we showed were switchable between imperial (feet/miles) and metric(meters/kilometers). That would be easily modifiable.

**Comment by guidway** [comment]
One more question, when is the toolkit containing the scalebar expected to be released?

**Comment by rolson** [comment]
should be update 1 time frame
