### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by slayer531** [Esri/runtime-questions#137]
So I spoke to one of the lead guys, and he mentioned that there are approximately 120 people working on the runtime... As I walked away, I realized that I needed to ask another quetion...

How many lines of code makes up the runtime (from the c++ API through to the individual languages)?

Also, is the runtime c++ API built on top of ArcObjects?

**Comment by eric906** [comment]
I will allow @EuanCameron to speak for the number of lines of code. 

As for the Runtime C++ API, No...it is not built on top of ArcObjects. As for the Local Server piece, yes. There are some ArcObjects under the covers in there to support things that have not migrated over to Runtime Core yet, but there is no programmatic access to these in Runtime. They are completely hidden.
