### ISSUE TITLE
v100 + Xamarin.Forms on Windows 7 or 8?

### ISSUE THREAD

**Issue by jfullmer23** [Esri/runtime-questions#138]
Will v100 of the runtime work with Xamarin.Forms on Windows 7 or 8, or will this only work with Windows 10 and up?

Deploy and run an application on Windows 7 or 8, not the dev environment.

**Comment by dotMorten** [comment]
Xamarin.Forms runs on Android, iOS and UWP. So for Windows (UWP) that means Windows 10.
To run on Windows 7 and 8, you must use the WPF part of the .NET API, instead of Xamarin.Forms.
