### ISSUE TITLE
Maplex support in Runtime 100.x MMPK / VTPK

### ISSUE THREAD

**Issue by sweihs** [Esri/runtime-questions#139]
What about support of Maplex Labeling Engine in Runtime 100.x regarding both mmpk and vtpk? Please provide Information on your future plans

**Comment by EuanCameron** [comment]
We do not have plans to add Maplex support to the runtime, however we will continue to enhance the new runtime labeling engine.   We also plan to add the runtime's labeling engine to ArcGIS Pro.  This will allow you to get a true preview of your maps in Pro before packaging and use with Runtime apps.

Maplex is a fully features engine where maximizing label placement for the creation cartographic products is primary.   The runtime labeling engine is more balanced on performance vs maximizing labels placed.
