### ISSUE TITLE
Reasons to ditch Engine for Runtime 100

### ISSUE THREAD

**Issue by byang007** [Esri/runtime-questions#140]
Have friends who are still using Engine SDKs and it seems hard to convert them to Runtime 100. 
Can anyone give enlightenments on why Runtime 100 should be the way forward? 

Anything that Engine SDKs are so good at that Runtime 100 can't perform?

Thanks in advance :)

**Comment by eric906** [comment]
It's been almost a year. Sorry for the delay!

Engine has been an awesome product for Esri and our users, for many years. Powerful, complete. I personally love it. 
However,...
Today's computing devices keep advancing quickly. Remember back in the day? Cell phones were these flip things, with no storage, and could barely browse the internet? No way could Engine run on a phone back then.
Today, these devices are capable of the things only PCs and Laptops were capable of, and people are using them as replacements for PCs. We needed a modern developer API and Runtime that could take advantage of these environments. Engine is MS COM, 32-bit only, supports Java/.NET/C++ languages, and only runs on Windows and Linux. For Linux, you need Wine to emulate a Windows architecture just for ArcObjects to run. Pretty ugly. While Engine is extremely granular and can do everything, this also makes for a complex API, hard to adopt quickly and easily. It's "COM-ness" also bleeds into the Java and .NET APIs. Something many developers have complained about over the years.
ArcGIS Runtime is a more streamlined, easier-to-use API, supported on 32-bit, native 64 bit, and ARM chipsets. It runs on Windows, Linux, and macOS desktops/laptops. It runs on iOS, Android, and Windows hand-held devices. You can write Runtime applications once and compile them for 5 different platforms easily using Qt, Xamarin, or Java. The languages it supports are Java, JavaFX, Android's Java, C#/.NET, Objective-C, Swift, Kotlin, Qt C++, and QML. - all of these APIs are based on the exact object model....making it easy to jump from programming with one to programming with the other if necessary.

Engine is no-longer the modern architecture for today's computing devices, nor is it compatible or able to keep up with Esri's Web GIS technology and approach. That is one of the main motivations for designing ArcGIS Runtime, to provide a platform that is agile enough to carry our developers into the future.

So...the capabilities of Engine needed to translate to the ArcGIS Runtime. Bringing ALL of these capabilities across has taken some time, longer than expected, but we are there now, for the most part. Engine developers now have a platform to migrate to.

I hope this helps!

Speaking of migration, here are some migration resources we hope you find helpful:

These Guide topics cover general migration concepts:
•	Java - https://developers.arcgis.com/java/latest/guide/migrate-to-100-x-from-10-2-x.htm
•	.Net - https://developers.arcgis.com/net/latest/wpf/guide/migrate-to-100-x-from-10-2-x.htm 
•	Qt - https://developers.arcgis.com/qt/latest/qml/guide/migrate-to-100-x-from-10-2-x.htm 
•	Android - https://developers.arcgis.com/android/latest/guide/migrate-to-100-x-from-10-2-x.htm 
•	iOS - https://developers.arcgis.com/ios/latest/swift/guide/migrate-to-100-0.htm 
•	macOS - https://developers.arcgis.com/macos/latest/swift/guide/migrate-to-100-0.htm 

Hands-on learning: From a practical standpoint, these DevLabs help developers understand migration workflows:
•	Dev Labs - https://developers.arcgis.com/labs/

Helpful videos:
•	Understanding the ArcGIS Runtime v100 architecture: https://www.esri.com/videos/watch?videoid=K6eObVkVeyc&channelid=UC_yE3TatdZKAXvt_TzGJ6mw&title=arcgis-runtime:-an-introduction-to-the-api-and-architecture 

•	Tips and techniques for planning your application migration to the runtime 100: https://www.esri.com/videos/watch?videoid=h1lyaH00G6A&channelid=UC_yE3TatdZKAXvt_TzGJ6mw&title=arcgis-runtime:-migrating-from-arcgis-engine 

License model:
•	https://developers.arcgis.com/arcgis-runtime/licensing/

Product Life Cycles:
•	https://support.esri.com/en/Products/Developers/native-runtime-sdks/arcgis-runtime-sdk-for-java/100-2-0#product-support
