### ISSUE TITLE
Any plans to use Runtime to create SOEs or SOIs for ArcGIS for Server

### ISSUE THREAD

**Issue by gmarbury** [Esri/runtime-questions#141]
Any plans to use Runtime to create SOEs or SOIs for ArcGIS for Server or will ArcObjects continue be the supported path to do this.

**Comment by johnselkirk** [comment]
The ability to inject functionality into the sync process would be good for example. We have the need to update related tables (not being 2-way synchronized) based on attributes of the incoming features.

**Comment by slayer531** [comment]
Runtime in the server environment will be quite the treat!

**Comment by eric906** [comment]
We have certainly received a lot of interest in the ability to use Runtime in a Server/Services context! Thank you for weighing in on this.

As it stands today, there are not plans for Runtime to support such use cases.

ArcObjects SDKs for Java and .NET continue to be the products to use for extending services, SOEs and SOIs.
