### ISSUE TITLE
Offline API documentation

### ISSUE THREAD

**Issue by guidway** [Esri/runtime-questions#142]
When installing the ArcGIS Engine SDK's, offline help would also be installed. This is extremely helpful when having internet issues or developing in certain environments. Are there any plans to provide offline API documentation for Runtime (i.e. local to the developer machine)?

**Comment by mbranscomb** [comment]
Each Runtime SDK provides an offline equivalent of their API Reference and Guide available to download from https://developers.arcgis.com/downloads/. 

For .NET we currently provide offline doc as .CHM files and PDFs. But we are always looking at ways we can improve our doc and we welcome your feedback. 

Cheers

**Comment by guidway** [comment]
Thanks Mike, great to know!
