### ISSUE TITLE
More better simple samples to exercise building box functions

### ISSUE THREAD

**Issue by t-foster** [Esri/runtime-questions#144]
Most of the apps shown here and on the samples hit hard on new features but don't exercise other functionality like the geometry engine and all the functions inside of that.

**Comment by anttikajanus** [comment]
From a runtime side, we provide couple different places where we highlight the usage of the API

- Samples such as https://github.com/Esri/arcgis-runtime-samples-dotnet/ are designed to focus more on the API level usage and simple samples how to work with the API on the lower level
- DevLabs such as https://developers.arcgis.com/labs/browse/?topic=any&product=NET are short 15 minutes labs that you can do to learn more about the specific areas. 

We are happy to hear feedback related both to the DevLabs and Samples. Are we missing samples related to some areas of the API? What would you like to see there?

**Comment by t-foster** [comment]
I suggested this to Eric Bader offline about having an example of stuff like the canonical intersect example http://desktop.arcgis.com/en/arcmap/10.3/tools/analysis-toolbox/how-intersect-analysis-works.htm just using runtime functions.

**Comment by shellygill** [comment]
@t-foster - I'd add that our team is actually working on our backlog of samples right now, and there are a number of new samples currently going into Runtime SDKs that cover a number of geometry engine functions - things like geodesic operations, cut method, and spatial relationships. More will be added over time - do let us know the specific functions you'd most like to see covered.

**Comment by t-foster** [comment]
Recommend closing this issue as resolved.

**Comment by shellygill** [comment]
Thanks @t-foster I will close this issue, please post back if there's any specific samples you'd like to see added in future.
