### ISSUE TITLE
What does High Accuracy GPS Support mean?

### ISSUE THREAD

**Issue by david-chambers** [Esri/runtime-questions#146]
In the "road ahead" session we saw a bullet for high accuracy gps support.  What will it look like to invoke the high accuracy gps api?

**Comment by madmapper** [comment]
Will this be using the SDK from Aman enterprises and include support for the little NMEA dongle he sells?  If so will it include support for other serial-type devices (aka rangefinders and the like?)

**Comment by mbranscomb** [comment]
@david-chambers That feature is still in design and is on the roadmap for a future release. That means it's difficult to say what the API will look like specifically. Broadly it covers additional support for parsing a NMEA feed, a new GNSS data source, and a perhaps a location object.

@madmapper The goal is to enable support for a range GNSS devices.
