### ISSUE TITLE
Better explanations of why errors occurred 

### ISSUE THREAD

**Issue by t-foster** [Esri/runtime-questions#147]
Sometimes in development you hit an error occurred signal where you get an error code number with sometimes a message or additional message. Is there a way to add to the documentation some explanations of common error codes, their sources, and typical means to mitigate/solve them?

**Comment by rexhansen** [comment]
We do provide a list of errors and codes associated with Runtime: 
Example: https://developers.arcgis.com/net/latest/wpf/guide/platform-error-codes.htm   

We can look at enhancing details where possible.  If there's a specific situation you encountered and needed more info, let us know.

**Comment by t-foster** [comment]
I do most of my development offline and use the qt assistant pre compiled help which only has the api reference with none of the guide content.  Would it be possible to add that in with the delivery in the sdk/doc/ directory?

**Comment by mbranscomb** [comment]
@t-foster The Platform error codes topic is included in the offline Guide doc downloadable from https://developers.arcgis.com/downloads/apis-and-sdks.
