### ISSUE TITLE
What native raster formats does the runtime support

### ISSUE THREAD

**Issue by grbsystems** [Esri/runtime-questions#148]
Can I ingest raster formats like GeoTiff or CADRG  into a map directly with the runtime from a folder on the device.  Is there a list of supported formats published anywhere?

**Comment by kerryrobinson** [comment]
Yes, CADRG and GeoTIFF are directly supported using the [RasterLayer](https://developers.arcgis.com/qt/latest/qml/guide/add-raster-data.htm#ESRI_SECTION1_5BEB04A0A0924F15A2B5AF1ECBD9ADC0) class.

A list of supported data formats can be found [here](https://developers.arcgis.com/qt/latest/qml/guide/add-raster-data.htm#ESRI_SECTION1_D3B90253C5A945BEB79E521C344E945D).
