### ISSUE TITLE
Is the SQLite database used for the runtime geodatabase easily viewable with tools like SQLite Expert or are the table and field names set up using keys that are stored somewhere and will need to be looked up?  

### ISSUE THREAD

**Issue by CivilDude** [Esri/runtime-questions#15]

**Comment by madmapper** [comment]
Yes - change the extension to SQLite and dig in.  Not sure what the official answer is from Esri but we have done this many times for diagnostics.

**Comment by EuanCameron** [comment]
The internals of the mobile geodatabase stored within sqlite can be viewed using many tools that support sqlite.   As always we don't encourage direct editing of the tables.

**Comment by shanergi** [comment]
Whenever I try to open a .geodatabase file in a SQLite browser I get "file is encrypted or is not a database". I've tried Sqlite Administrator, the Firefox SQLite add on, and SQLite Expert personal edition. Does anyone have an example I can open that has worked for them? I've only used .geodatabases that I have found in various Runtime for .NET related gitub repos.

**Comment by doneill** [comment]
@shanergi As @EuanCameron says, you should only use these tools to view/inspect your *.geodatabase file. Having said that, there may be something wrong with your *.geodatabase file, but on many occasions I have had issues opening a *.geodatabase file in [sqlitebrowser](http://sqlitebrowser.org/) yet the same file opens fine using [SQLite Pro](https://www.sqlitepro.com/).  But I can open the same *.geodatabase file in SQLite Manager for Firefox which you reported as not working so maybe it is the *.geodatabase file.

BTW:  You should not have to change the extension of your *.geodatabase file.
