### ISSUE TITLE
Will the .net runtime support the new 'broadFileSystemAccess' setting for UWP?

### ISSUE THREAD

**Issue by rzeckoski** [Esri/runtime-questions#150]
Currently geodatabases can only be opened in an application's 'own' folder (e.g., localstate, application shared local) - they cannot be opened from a folder the application has declared access to (e.g., pictures library).  This creates quite a problem for sharing data.  Will the .net runtime for UWP be able to open geodatabases anywhere on the file system if the application has declared the new broadFileSystemAccess capability?

https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by dotMorten** [comment]
Yes.

**Comment by dotMorten** [comment]
So I finally had a chance to try this out after all the devsummit rush. Unfortunately the news aren't so great. It doesn't work with the Runtime at this point. I'm following up with Microsoft to see if this is a bug or whether we need to make changes to the runtime (it's failing in a 3rdparty component so we might not actually be able to make these changes, but I will do my best).

**Comment by david-chambers** [comment]
We're rooting for you @dotMorten! Did you hear anything back from Microsoft?

**Comment by dotMorten** [comment]
@david-chambers Yes I did. It's on their radar, but not supported yet (the new capability is just a small step in that direction). I looked into what we could do to support it in Update 3, and unfortunately at this point it's just not possible.
To put things in perspective, even with this capability you can't even do something as basic as using the .NET API's `System.IO.File.ReadAllText`. You have to still use the old StorageFile API, which sort of defeats the purpose.

To be honest, I'm was rather surprised myself how limited this new capability was (for now).

**Comment by simon-fisher** [comment]
@dotMorten I'm guessing this still isn't supported?  I was just trying to implement using a shared location for gis data using broadFileSystemAccess, and cannot get the map to load any data from a location other than the app folder.  Any update on if this will be supported in the future?
