### ISSUE TITLE
What are the technical limitations of implementing local server in UWP and Xamarin?

### ISSUE THREAD

**Issue by david-chambers** [Esri/runtime-questions#151]

**Comment by mbranscomb** [comment]
Local Server is supported with the WPF API only. It is currently not possible to use Local Server in UWP or in Xamarin (Android, iOS, or UWP).

**Comment by mbranscomb** [comment]
Local Server is supported with the WPF API only. It is currently not possible to use Local Server in UWP or in Xamarin (Android, iOS, or UWP).

Please let us know if there is functionality you need on other platforms but that functionality is currently only available with the LocalServer.... here or on Geonet (https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).
