### ISSUE TITLE
HttpClient handler

### ISSUE THREAD

**Issue by jeremy-bridges** [Esri/runtime-questions#154]
Is there plans to have an API to inject a custom http handler?

**Comment by jeremy-bridges** [comment]
Also, is there plans to reduce the number of new instances of HttpClient that the runtime creates? There's overhead in making a lot of those:

https://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client

**Comment by dotMorten** [comment]
Yes. Update 3 will have a way to do this.
With Xamarin.Android you can use the `XA_HTTP_CLIENT_HANDLER_TYPE` environment to use a different handler (this is normally set via the project settings, but can also be set to a custom type via code). That is documented here: https://developer.xamarin.com/guides/android/advanced_topics/environment/ and you can see the implementation here: https://github.com/xamarin/xamarin-android/blob/0c26b71339a1027902f72e3842077feb7d9c7d9b/src/Mono.Android/Android.Runtime/AndroidEnvironment.cs#L319
