### ISSUE TITLE
Pre-Planned Offline Content, Features of Interest

### ISSUE THREAD

**Issue by battlezone77** [Esri/runtime-questions#163]
Will there ever be a way to generate pre-planned areas to take features offline that have a specific attribute value?

**Comment by anttikajanus** [comment]
This should work at the moment. If you are using python API to create the areas, you need to use definition expression on the feature layer on the map but not having multiple layers pointing into the same feature service. You have more control setting the expression using REST API to create the areas. You can find the service description from https://developers.arcgis.com/rest/packaging/api-reference/create-map-area.htm and https://developers.arcgis.com/rest/packaging/api-reference/setup-map-area.htm. When setting the area, provide layerQuery property to limit the features you want to get.
