### ISSUE TITLE
Is there any chance that the minimum Android API level will go above the current 16 in the June or December/January release?

### ISSUE THREAD

**Issue by pgowdy1** [Esri/runtime-questions#166]

**Comment by zwaap** [comment]
The minimum requirement will move up to API 19 at the 100.3 release.  You can find the deprecation notice for the currently supported API level for Xamarin Android [here](https://developers.arcgis.com/net/latest/wpf/guide/release-notes.htm#ESRI_SECTION1_5DB21B7CC9D24B1894B590EEB9C46DBD) and native Android [here](https://developers.arcgis.com/android/latest/guide/release-notes.htm#ESRI_SECTION1_5DB21B7CC9D24B1894B590EEB9C46DBD).
