### ISSUE TITLE
Is there a way to pull elevation data from a DEM in a map instead of a scene?

### ISSUE THREAD

**Issue by stephenrhea** [Esri/runtime-questions#168]

**Comment by mbranscomb** [comment]
@stephenrhea Support for the identify operation on raster data is on the roadmap for a future release. Currently the operations returning elevation values only work in a SceneView.

Depending on your target deployment platform, functional requirements, and workflow - you may be able to consider using geoprocessing scripts in conjunction with the ArcGIS Runtime Local Server component.
- https://developers.arcgis.com/net/latest/wpf/guide/local-server.htm
- https://developers.arcgis.com/java/latest/guide/local-server.htm
- https://developers.arcgis.com/qt/latest/cpp/guide/local-server.htm
