### ISSUE TITLE
x86_64 and arm64-v8a support for Android using .Net API?

### ISSUE THREAD

**Issue by chrisg32** [Esri/runtime-questions#169]
The Nuget package doesn't support these platforms starting at 100.1.0 (version 100.0.0 has runtime exceptions). [Documentation](https://developers.arcgis.com/net/latest/android/guide/system-requirements.htm) confirms they are not supported.

ETA on when we can see 64bit support?

**Comment by mbranscomb** [comment]
@chrisg32 It's on the roadmap for an upcoming release, as-ever dependent on testing and release certification. Unfortunately it's not possible to be more specific at this time. But we are aware of the future requirements for Google Play Store submissions.

For any new questions about ArcGIS Runtime SDK for .NET please use the [Geonet community site](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).
