### ISSUE TITLE
Ability to create editable map packages 

### ISSUE THREAD

**Issue by aarondick** [Esri/runtime-questions#17]
Is there any possibility down the road to have editable map packages?  Sync is great, but many offices in our organization have very slow bandwidth  and lots of ad hoc data collection.

**Comment by EuanCameron** [comment]
We do have this capability on our backlog.   There are many existing workflows (ArcGIS Engine, ArcPad based) that do this and need the capability before moving over to ArcGIS Runtime based solutions.
