### ISSUE TITLE
Linear Referencing - Develop Custom Implementation?

### ISSUE THREAD

**Issue by TomVlasschaert-CP** [Esri/runtime-questions#171]
I have seen the four closed issues re Runtime SDK support for Linear Referencing.  Most indicate it is not an priority for ESRI.

We have an app that needs to run disconnected and perform functions to:

- Determine an M-distance coordinate for a given M-Aware Polyline
- Find the M-distance for a point on a given M-Aware Polyline

Since the SDK Points and Polylines classes support M values, I am considering developing my own implementation of these functions.  I am aware that it is possible to user a LocalServer solution but (1) this is overkill for us and (2) creates a licensing issue.

My question is;  is making our own implementation as simple as I think?  Is there anything more to it than running through the line segments, adding up the M values, and performing a ratio on the appropriate line segment?  I am wondering if I might be failing to consider something.

Thank you in advance.

Tom Vlasschaert

**Comment by mbranscomb** [comment]
@TomVlasschaert-CP This repo is not actively monitored.

Please post your question in the Geonet forum for the product you are using: https://community.esri.com/community/developers/native-app-developers/places.
