### ISSUE TITLE
iOS SDK - Custom callouts as view controllers

### ISSUE THREAD

**Issue by yar1vn** [Esri/runtime-questions#18]
On an iPad I use UIPopover presentation instead of a callout or popup to embed a view controller with adaptive behavior, dynamic sizing and segues. 

Will it be possible to use view controllers in callouts instead of simple views?

**Comment by maryharvey** [comment]
Yes you can add ViewControllers to a Callout. This was demonstrated in the "Advanced Tips and Tricks for iOS and OS X'  runtime session on Wednesday. 
This repo contains code for adding a popupview controller to a Custom Callout. Build and run the app and then take a look at the the Tip 18. Custom Callout.
https://github.com/ArcGIS/tips-and-tricks-ios
