### ISSUE TITLE
.Net and non-Windows OS-es (.Net Community & OSS)

### ISSUE THREAD

**Issue by Umbrah** [Esri/runtime-questions#19]
Microsoft has announced that the full .Net runtime framework (CLR, JIT-compiler, base class libs, garbage collect) will be ported to Linux, MacOS X, and other platforms, alongside community editions of Visual Studio: how will this impact the .Net runtimes from ESRI?

**Comment by Umbrah** [comment]
Added link (reference): http://www.wired.com/2014/11/microsoft-open-sources-net-says-will-run-linux-mac/

**Comment by dotMorten** [comment]
Unfortunately Microsoft is not open source or porting all components including WPF to these platforms, which means we won't be able to support the .NET runtime on Mac and Linux.
Having said that it has a huge impact on Xamarin, which over time will be bringing these libraries in and replace Mono, and use the Roslyn compiler. This will have an effect on our upcoming Xamarin offering, ensuring greater compatibility between apps running on .NET and the Mono runtimes.
