### ISSUE TITLE
.NET Runtime and Shapefiles

### ISSUE THREAD

**Issue by wirebarbed** [Esri/runtime-questions#2]
My client (not me) wants to use shapefiles in an app...

Could you clarify a note about shapefiles in the .NET Runtime documentation?

"It is recommended to always set the SpatialReference for the Map when using a FeatureLayer based on a local disk based FeatureTable such as a ShapefileTable. The reason is that the visual elements of the FeatureLayer may not display if the Shapefile is not based on the SpatialReference WKID of 3787 (aka. Web Mercator). By specifying the Map's SpatialReference to be exactly the same at the ShapefileTable, you will be assured that it displays visually in the Map."

Does this mean the only way to view shapefiles is using Web Mercator?

**Comment by dotMorten** [comment]
Any projection is supported. However FeatureTables does not support projection on the fly so the Map must the same spatial reference as the shape file for the shapefile to render.
