### ISSUE TITLE
Change base map on the fly having different spatial 

### ISSUE THREAD

**Issue by soundraj** [Esri/runtime-questions#20]
The requirement is to change any spatial base map on fly (mostly online) .  One method suggested from Esri is rebuild new map starting with basemap so that it can hold the corresponding spatial. But it takes long time since the app has too many layers with too many items.

Is it better to fix the map to one specific to one spatial (e.g. 102100) and just remove base map and re-add and the new base map projected to the map's spatial.

What spatial is recommended in this case.  4326 or 102100?

**Comment by EuanCameron** [comment]
Changing of the maps spatial reference and have all the layers in the map re-projected on the fly is not supported by the runtime.
