### ISSUE TITLE
Will AppStudio make it easier or help me with getting my app into the Apple App Store?

### ISSUE THREAD

**Issue by azatrain** [Esri/runtime-questions#21]

**Comment by EuanCameron** [comment]
Building apps from the templates provided with AppStudio do may the job easier.   One reason for this is that for each template included Esri has published at least one app based on it already to the Apple App Store, so we know they will get approved from a technical stand point.   This means that if you submit an app, you can feel confident that there should be no major issues.

We are looking at how we can further improve this to make it even easier for our users.
