### ISSUE TITLE
Future of SDK variety

### ISSUE THREAD

**Issue by KsmithGMB** [Esri/runtime-questions#22]
There seems to be a trend to move towards device/platform less development with html5 and the app studio.  Will we see a similar trend and a reduction in the variety of sdks?

**Comment by EuanCameron** [comment]
We don't play favorites when it comes to SDK technologies.   Today there are distinct benefits in using native APIs when building apps, and so we support the popular native APIs.    Overtime the developer community will pick the technologies most appropriate for their needs, and we will support them.   That may mean consolidation, it may mean an increase in SDKs.   Time will tell.
