### ISSUE TITLE
Mobile Map Packages

### ISSUE THREAD

**Issue by esride-mag** [Esri/runtime-questions#23]
1. How much smaller will the MMP be than the offline cache at the Moment?

2. When I want to update a single part of a MMP (eg the WebMap or Basemap), will I be able to update just the changed content? Or do I have to recreate the whole MMP?

**Comment by EuanCameron** [comment]
The size of the package obviously depends on what's in it and what it is used for.   Mobile Map Packages do support a new compressed data format that can be used for read only data, and if that is your need you will see a significant reduction in size.    If your need is to edit the data, there will be little change in the size.

A mobile map package does not only contain the Map, Layers and their associated data, it can also contain a street network and locator.
