### ISSUE TITLE
Mobile Map Package export service

### ISSUE THREAD

**Issue by m4tnayrb** [Esri/runtime-questions#28]
Will the geoprocessing function used by ArcGIS Pro to create a Mobile Map Package eventually be a Portal hosted function?

**Comment by EuanCameron** [comment]
There are currently no plans to deliver this in 2015.    There are plans to support taking your map offline with a simple OfflineMapTask for the Quartz release, which will have similar capabilities for the Map and layers within it.   It will not support clipping a street network and locator.

**Comment by coryeicher** [comment]
We are very interested in increasing support in the runtime SDKs/Esri stack for 'disconnected web maps' managed thru Portal... apps too managed in portal, so also ability to configure standard/custom app tools using Portal.
