### ISSUE TITLE
Is the long term goal to replace the Soc on the server?

### ISSUE THREAD

**Issue by hwernstrom** [Esri/runtime-questions#29]
Is the long term goal to replace the Soc on the server with the runtime?

**Comment by eric906** [comment]
There are no current plans to replace the underlying SOC implementation with Runtime technology. The Runtime technology is specifically designed for building apps that run on client-end devices. It is tailored for taking advantage of resources (GPUs, display, etc) on a client device; a desktop, laptop, embedded or mobile device. It is not designed for use in a server system context or environment.
