### ISSUE TITLE
Setting up a Runtime license with a Visual Studio 2013 VB applicaiton.

### ISSUE THREAD

**Issue by Jim1099** [Esri/runtime-questions#30]
Is there any difference in the way the license manager is set up with the new runtime, as compared to how it was set up with ESRI 10.2.2 Engine?

**Comment by dotMorten** [comment]
Yes they are different - Licensing is the same on all the runtime, but different from Engine.
Full documentation how to license your app for basic or standard functionality is here:
https://developers.arcgis.com/net/desktop/guide/license-your-app.htm
