### ISSUE TITLE
spatial reference systems

### ISSUE THREAD

**Issue by bootrider** [Esri/runtime-questions#32]
Will runtime have, in some future, the same capabalities to handle spatial reference systems as arcobjects/arcengine has?

**Comment by willcrick** [comment]
Not exactly the same but very similar. We already support most spatial references and on some platforms you can also use grid based transformations between spatial references. Full information can be found in the product doc, e.g. is here:
https://developers.arcgis.com/java/guide/geographic-coordinate-systems.htm
