### ISSUE TITLE
Bing and Google Maps support 

### ISSUE THREAD

**Issue by soundraj** [Esri/runtime-questions#33]
1. Do we still support Bing maps in .NET SDK?

2. Can I load google maps as well?

**Comment by dotMorten** [comment]
1. Yes. See doc here https://developers.arcgis.com/net/desktop/api-reference//html/T_Esri_ArcGISRuntime_Layers_BingLayer.htm
2. It's technically possible, but Google's license terms prevents you from this - you would have to license content first from Google.
