### ISSUE TITLE
Is there any way to detect/manage IDs of offline sync enabled geodatabases?

### ISSUE THREAD

**Issue by ReedHunter-Wsdot** [Esri/runtime-questions#35]
I'm looking at the likelihood of close to a thousand simultaneous offline sync enabled geodatabases among a community of iOS app users.  I have just learned of the need to register and unregister sync enabled geodatabases with the feature service using the AGSGDBSyncTask.  Is there any way for me to monitor how many offline geodatabases are registered for synchronization with the server?  On the chance that there will be orphaned sync IDs for any reason (for example: a bug in the app), is there some mechanism to manage and retire offline geodatabase sync GDB IDs, or to detect sync GDB IDs that haven't been in use?

Is there an impact to performance if I cannot manage these IDs?
Thanks

**Comment by ReedHunter-Wsdot** [comment]
Found two parts of an answer myself, though not the entire picture yet: 1. the rest endpoint of a feature service includes a link for replicas in that feature service.  2. There is a property of an offline geodatabase called the .syncEnabledGeodatabaseID.  This property maps the ID of the offline geodatabase to one of the replicas in feature service.  The current missing link is determining for an existing set of replicas how long they have been idle, meaning nobody has attempted to sync with a given replica.  If a replica becomes idle for say 6 months, then it may be ok to delete.

**Comment by exolvi** [comment]
If you are at the feature service endpoint under the list of replicas, you should be able to click into each replica for details and you'll get a bunch of information about it, including the parameters for the replica, but also when the replica was created and when the last sync was performed.

![image](https://cloud.githubusercontent.com/assets/6610138/8860693/fb54de82-314a-11e5-93b8-581347412d7d.png)
