### ISSUE TITLE
Authentication for 3rd party (Marketplace) apps

### ISSUE THREAD

**Issue by artisanglobal** [Esri/runtime-questions#39]
It would be great if we as developers could authorize specific ArcGIS Online (or Portal) users for our marketplace apps. Users would then have just one login to:
1) Determine if they are authorized to use our app, and 
2) Access ArcGIS Online (or Portal) content

**Comment by willcrick** [comment]
This is possible today. If the user has access to the portal item that represents your app, then they are authorized to use it.
