### ISSUE TITLE
Q: Can we automatically assume support for fully interchangeable and mixed connection to/consumption of both Portal for ArcGIS and ArcGIS Online? (UC2015 Pre-Con Quartz Workshop)

### ISSUE THREAD

**Issue by geodevguy** [Esri/runtime-questions#40]

**Comment by willcrick** [comment]
You can access both AGOL and a Portal for ArcGIS (both referred to as Portals) using the runtime portal api. But, it is best practice to only be logged in to a single Portal at a time.
