### ISSUE TITLE
Update or remove Apache HttpComponents

### ISSUE THREAD

**Issue by caporossi** [Esri/runtime-questions#44]
ArcGIS Runtime 10.2.x for Java uses some internal dependency, for example Apache httpcomponents in version 4.0.1. This is an old version, the most recent is the 4.5

We use ArcGIS Runtime in larger applications built using at the same time different COTS (same JVM) , if these COTS use the same dependency but in newer versions ArcGIS Runtime for Java does not work, this is a big problem.

In the new version will you update or remove these dependency to allow the use of arcgis Runtime for Java in larger application.

**Comment by caporossi** [comment]
In this version you use:
commons-codec-1.6.jar last is 1:10
commons-logging-1.1.3.jar the latest is 1.2
gson-2.3.1.jar the last is the 2.3.1 this is OK
httpclient-4.3.6.jar the latest is 4.5
httpcore-4.3.3.jar the latest is 4.4.1

To use ArcGIS Runtime for Java in complex desktop application there are two solutions:

1) remove these dependencies
2) At each release upgrade dependencies to the latest version .

**Comment by mbcoder** [comment]
We will review and update to later versions before we release the Beta 2 release.
