### ISSUE TITLE
Q: When you don't need a map, just a wrapper around service calls...

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#45]
We have cases where we don't need a map but have an application that needs results from services (e.g. routing).  The Runtime SDK is a nice Wrapper around services.  Since Quartz revolves around maps, what do you recommend as the approach?

We are prototyping an assembly that is a library, not an UI application, that encapsulates the calls to ArcGIS Server.  We need this because we need to integrate into an existing application and be able to switch out an old Net Engine based services to use ArcGIS Server instead.  It was tricky to get the manifest to build in that case.  How will that be done in Quartz?

**Comment by willcrick** [comment]
you can use the service metadata objects, which in future versions of quartz will be "loadable" and you can create from a URL. You can also use layers and tasks on their own without a map.
