### ISSUE TITLE
For the long term, which runtime data formats should we invest in (for disconnected applications)?

### ISSUE THREAD

**Issue by coryeicher** [Esri/runtime-questions#47]
Which vector (read/write) and tile data formats should we invest in for the long term? We have a data/configuration 'mobile provisioning solution' which deals w/ read only vector data, read/write vector data, and tile data. We are currently using .geodatabase and .tpk formats, and we're happy. Are these solid choices for the long term?  

Main criteria for us are formats which with full featured support in the SDKs and also 'friendly' to our mobile provisioning system. Said system is semi-automated, with map configuration steps performed by humans using Esri desktop and Portal, automated parts either/both of using Esri py and ArcGIS Server REST apis.

**Comment by willcrick** [comment]
Mobile map packages, mobile geodatabases (using sqlite) and .tpks (and new .vtpk's).s
