### ISSUE TITLE
Elevation in SDK

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#5]
Any plans to add elevation to the location functionality in the sdk?  Currently have to use core location to get to this info.

**Comment by eric906** [comment]
Are you referring to Z values in geometry?

**Comment by madmapper** [comment]
Yes - currently in the iOS sdk there is no z information in the location object
- Mike

On May 12, 2015, at 1:03 PM, Eric Bader <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you referring to Z values in geometry?

**Comment by eric906** [comment]
Ah. Thanks Mike.
Quartz will support Z values in the geometry model for iOS and MacOS.

**Comment by shellygill** [comment]
Just a little more info courtesty of a colleague - the position returned from the Quartz device location API will include a z value if elevation information is available from the platform location service. With a 3D map it will be a simple API call to get an elevation from the surface at a specific coordinate/point.
