### ISSUE TITLE
Has the iOS Quartz project setup changed slightly from previous releases?

### ISSUE THREAD

**Issue by phpmaps** [Esri/runtime-questions#50]
The 10.2.6 online documentation, [Install and set up](https://developers.arcgis.com/ios/objective-c/guide/install.htm), says to go to `Build Settings` and set `Framework Search Paths` to `$(HOME)/Library/SDKs/ArcGIS/iOS/`.  For me this did not work.  I had to use this path `$(HOME)/Library/SDKs/ArcGIS/iOS/Frameworks/Static` provided the `default` install.

See image

![image](https://cloud.githubusercontent.com/assets/2159502/8763451/222b11c8-2d51-11e5-8bbf-2281f1797072.png)

**Comment by dg0yal** [comment]
Yes, its now in a new subfolder "static". 
Mentioned in the quartz release notes under the [xcode project changes section](https://developers.arcgis.com/ios/beta/swift/guide/release-notes.htm#ESRI_SECTION1_6ED87C0F1F3649309421B7B735FCFC06)
