### ISSUE TITLE
android-local-maven.zip doesn't exist

### ISSUE THREAD

**Issue by Zian** [Esri/runtime-questions#51]
In the Android README instructions, step 4 says to "Extract the contents of android-local-maven.zip"

There's no such file in the download from Box.

**Comment by doneill** [comment]
Typo, the file you need is **esri-maven.zip**.  And more info, you need to copy the contents of that folder to a **com/** directory in your maven repository.  If you don't have a maven repository but you have maven installed run the following from a command line terminal:  

```
$ mvn
```

That will create your maven respository under **/[USER]/.m2/repository** on mac and **C:\Users[USER].m2\repository** on win.
