### ISSUE TITLE
will there be a friendlier way to create colors in Android?

### ISSUE THREAD

**Issue by coryeicher** [Esri/runtime-questions#54]
will there be a friendlier way to create colors in Android? int parameters, hex color, enum values?

the below code (or similar) is the only code I found that worked... not super friendly

```
private MarkerSymbol getMarkerSymbol() {

    byte red = (byte)255;
    byte green = (byte)0;
    byte blue = (byte)0;
    byte alpha = (byte)255;

    RgbColor rgbColor = new RgbColor(red,green,blue,alpha);

    MarkerSymbol markerSym = new SimpleMarkerSymbol(rgbColor,12, SimpleMarkerSymbol.Style.DIAMOND);
    return markerSym;
}
```

**Comment by caporossi** [comment]
the same problem with the Java version.

**Comment by willcrick** [comment]
at beta 2 we have changed the color api. look out for it (its much more friendly).
