### ISSUE TITLE
Low quality basemap appearance w/ AGSMapView::setViewpoint 

### ISSUE THREAD

**Issue by phpmaps** [Esri/runtime-questions#55]
I am disappointed about quality of the Esri basemaps.  Viewpoint object, since scale is a parameter, seems to introduce something that could be perceived as bad looking maps.  I think the goal should always be to show the best looking maps, with the one exception being the lowest scale level.

![image](https://cloud.githubusercontent.com/assets/2159502/8764002/8dc338a8-2d6e-11e5-900b-1e9a3ee256c6.png)

**Comment by madmapper** [comment]
They look much better on an actual device

**Comment by phpmaps** [comment]
![image](https://cloud.githubusercontent.com/assets/2159502/8768081/16f99c16-2e28-11e5-846a-2c20a34be56a.png)

**Comment by phpmaps** [comment]
More on this issue of Basemap visualization - reported by client in Europe.  @justincolville  - ideally the need to to figure out a way to always fill the screen.  

![image](https://cloud.githubusercontent.com/assets/2159502/9012866/12593308-376d-11e5-8729-2cff630ac0bb.png)

**Comment by willcrick** [comment]
at beta 2 we will have a new property on tiled layers to allow the control of this. watch this space.
