### ISSUE TITLE
Authentication required on public service w/ iOS SDK

### ISSUE THREAD

**Issue by phpmaps** [Esri/runtime-questions#59]
Adding a AGSFeatureLayer to the map pops a popup to login even though the service is public.

```
NSURL *url = [NSURL URLWithString:@"http://sampleserver6.arcgisonline.com/arcgis/rest/services/SampleWorldCities/MapServer/0"];
serviceFeatureTable = [[AGSServiceFeatureTable alloc] initWithURL:url];
fl = [[AGSFeatureLayer alloc] initWithFeatureTable:serviceFeatureTable];
[agsMap.operationalLayers addObject:fl];
```

**Comment by dg0yal** [comment]
There is a bug with how the feature layer is querying the service. As a result, an authentication challenge is being incorrectly issued. Logged a bug for it. Thanks for reporting.
