### ISSUE TITLE
Server SDK: SOI & runtime integration

### ISSUE THREAD

**Issue by Umbrah** [Esri/runtime-questions#6]
Hello team,

I became really interested in the integration of SOI's (which capture anything) and how authentication can play such a huge part in it. Granular security is such a huge deal for many of my clients! My question is:
* Will the integration of SOI's take any client adjustment?
* Will the SOI functionality take extents in account as well? EG: could I, other than just layers as given in the example, base my security around spatial extents?

**Comment by EuanCameron** [comment]
One of the strengths of SOIs is the fact that they can be deployed without changes to the Clients.
