### ISSUE TITLE
Offline Authentication

### ISSUE THREAD

**Issue by exolvi** [Esri/runtime-questions#68]
I realize we aren't to the offline piece yet, but are there plans to build the authentication manager to work disconnected?

**Comment by doneill** [comment]
No, as when you are offline you have everything you need locally so no need for credentials.  What is the workflow/pattern you are thinking about?

**Comment by exolvi** [comment]
For some of the projects we work on, we still have a need to authenticate while offline, just to access the application.  For the best user experience, we prefer to have users authenticate once and in the same manner regardless of network status.  This has changed for us since we have switched to OAuth and we had another way to do this before anyway, but always looking to leverage any new tooling.  Thanks for the response.
