### ISSUE TITLE
When Cluster will be supported in .net sdk?

### ISSUE THREAD

**Issue by soundraj** [Esri/runtime-questions#7]
Cluster is removed from .net sdk and when this can be added.

**Comment by EuanCameron** [comment]
Some of the advanced rendering and symbol options available in the WPF SDK have been removed from .Net.   These renderers were implemented using XAML, and had scalability issues.   The plan is to introduce these to the C++ runtime core and make them available to all runtime SDKs.   These advanced drawing functions are targeted for 2016.
