### ISSUE TITLE
Tech Preview vs Beta

### ISSUE THREAD

**Issue by exolvi** [Esri/runtime-questions#70]
Later this month there will be a tech preview for some of the platforms -- what is the difference between a tech preview and a beta?

**Comment by mbranscomb** [comment]
In our beta releases we strive to support specific complete workflows. In the case of Quartz Beta 1 this involved online/connected workflows. Quartz Beta 2 focuses on offline/disconnected workflows. The upcoming Tech Preview at the end of Q1 is for the new Xamarin SDK. This Tech Preview may not fully support all the workflows which we intend to deliver in Beta 2, but allows us to provide you with early access to this really exciting technology and get your feedback on the API/SDK as early as possible.
