### ISSUE TITLE
Offline Geodatabase Encryption

### ISSUE THREAD

**Issue by exolvi** [Esri/runtime-questions#71]
Is there support planned for offline geodatabase encryption in the future?  The use case is for ensuring all data is encrypted at rest for some clients that require it.

**Comment by dg0yal** [comment]
We don't have any plans (yet) to encrypt the contents within the geodatabase, but you can use on-disk encryption technology available on iOS & android (also windows??) to encrypt the geodatabase file. This is a developer opt-in option, and on ios you basically have to set some file attributes that tells the OS to protect the file and then the file is readable only while the device is unlocked.

More info about ios here - https://www.apple.com/business/docs/iOS_Security_Guide.pdf
