### ISSUE TITLE
Support for offline 3D in Quartz

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#74]
Will there be an offline 3D capability with Quartz?

**Comment by mbranscomb** [comment]
Yes, and you can see this already in the ArcGIS Runtime SDK for .NET 10.2.6 and 10.2.7 releases. Various file types are supported offline - including runtime geodatabases, KML, shapefiles, raster elevation datasets, tile packages. Additional local datasets will be available as support becomes available in the runtime Quartz release such as raster datasets for visualization (as opposed to just elevation), and geopackages.
