### ISSUE TITLE
Labeling - use Label definition from service

### ISSUE THREAD

**Issue by sweihs** [Esri/runtime-questions#76]
using .net sdk 10.2.7 I would like to use the Label definitions from service Definition. Featurelayer is based on synced down local Featuretable.

Is it possible in .net sdk 10.2.7? if yes how? if no when will it be available. Due to existing impl. and Project time scope, Waiting and migrating to Quartz is no Option.

**Comment by dotMorten** [comment]
@sweihs 
This should be supported already:
https://developers.arcgis.com/net/desktop/api-reference//html/P_Esri_ArcGISRuntime_Layers_FeatureLayer_Labeling.htm

The following layer XAML is rendering the label expression defined in the service (tested with 10.2.7):

``` xml
<esri:FeatureLayer>
    <esri:ServiceFeatureTable
         ServiceUri="http://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/MapServer/2" />
</esri:FeatureLayer>

```

**Comment by sweihs** [comment]
requirement is to do the labeling on the local geodatabase FeatureLayer (mobile device is offline and has data locally), i.e. not on the Web Service Featureservice Featurelayer

**Comment by dotMorten** [comment]
It should work with local tables as well, however you will have to explicitly turn them on when creating the feature layer from a table.
