### ISSUE TITLE
Local route and closest facility with traffic update?

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#78]
I have been told that local closest facility will be added to Quartz.
How hard/when can you include local closest facility solver with traffic update.
We need custom road impedance updates (linking to our existing system) which may bland standard or public traffic feeds with user set scheduled changes or overrides.

**Comment by willcrick** [comment]
Offline closest facility will come post Quartz.
To include offline closest facility with live traffic updates is not planned, as receiving the traffic updates requires a connection, therefore using a service for this makes more sense.
If you did want to update a local network with additional information like traffic, then you would have to recreate and redeploy the network.

**Comment by mikedorais** [comment]
Please step back and think of the use case.  We used to be able to directly
update road impedances on the old network dataset used by Net Engine.  Now
we cannot.  We cannot created and redeploy the network for every road
impedance update, even if it wasn't just traffic.  We have a system that
supports our 911 emergency communication centers being able to schedule
changes to road impedances as well as take feeds from traffic feeds like
DOT.  Our CAD (computer aided dispatch system) is an established system
used by 911 communication centers around the world.  We are not designing a
new small application that can be constrained to with Esri's current
product designs.  We have critical needs for many customers that depend on
older Esri technology that we are being forced off of.  We are looking for
Esri to provide a solution to this.  We are currently using ArcGIS Server
Network Analyst, but we are having difficulty matching the performance we
achieved by each client workstation using its own local copy with Net
Engine.

**Comment by willcrick** [comment]
Updating the network on the client is something that is planned for future releases.

**Comment by mikedorais** [comment]
Thank you.
