### ISSUE TITLE
Are there Icon animation in .NET sdk?

### ISSUE THREAD

**Issue by soundraj** [Esri/runtime-questions#8]
Are there any limitation or performance issues with it?  For example, can I animate 10,000 icons?

**Comment by dotMorten** [comment]
The runtimes does not have animation out of the box of symbols or feature location.
You can however update graphics on a frequent firing timer to get the effect of animation - Geometry updates are very performant - symbol and attribute updates a little less, but can still handle a large amount of frequent updates.

We do have symbol and geometry animation built-in on our future roadmap.
