### ISSUE TITLE
Direct access to a file geodatabase (.gdb folder)

### ISSUE THREAD

**Issue by Tape-Worm** [Esri/runtime-questions#80]
I'd like a much more straightforward way to use a file geodatabase. Currently, we're using ArcObjects to modify a file geodatabase template to add feature data to feature classes, and to build feature class schemas.

We're trying to move to 64 bit, and using the Runtime would be ideal, but manipulating feature data is proving to be less than straightforward.

Are there any plans to allow direct access to a file geodatabase directly via the runtime?

**Comment by eric906** [comment]
There are no plans at this time to extend database support to File Geodatabases. 
The only way to access file geodatabase data using the Runtime today is through the Local Server, using MPKs.
The way forward using the Runtime is the .geodatabase file (SQLite) and the mobile map package.
