### ISSUE TITLE
Extent Change vs Navigation Complete Events

### ISSUE THREAD

**Issue by faulconmjr** [Esri/runtime-questions#82]
How frequently is Extent Change Fired?
I'd like to better understand the need for the Navigation Complete Event.

**Comment by dotMorten** [comment]
Extent changes fires when the extent changes - that is up to 60 times pr second, as you are panning and zooming. Only perform very cheap operations in this event.
Navigation Complete fires when all navigation operations are complete (ie user interactions, mouse wheel, flick, navigation animations etc). This is where you can perform more expensive operations, for example query for what features are visible in the current view etc.
