### ISSUE TITLE
What is the proper way to use the loadAsync in the quartz runtime?

### ISSUE THREAD

**Issue by randallsutton** [Esri/runtime-questions#83]
Can you please explain the loadAsync and the proper way to use it?

For example this code crashes.

```
        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
            // create a marker symbol
            PictureMarkerSymbol pictureMarkerSymbol = new PictureMarkerSymbol((BitmapDrawable) ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_launcher));
            pictureMarkerSymbol.loadAsync();

            // get the point that was clicked and convert it to a point in map coordinates
            Point point = mMapView.screenToLocation(new android.graphics.Point(Math.round(e.getX()), Math.round(e.getY())));

            // create a graphic with the geometry and marker symbol
            Graphic graphic = new Graphic(point, pictureMarkerSymbol);

            // add the graphic to the graphics layer
            mGraphicsOverlay.getGraphics().add(graphic);

            return true;
        }
```

**Comment by randallsutton** [comment]
I'm not getting much of a stack trace, but here it is.

03-10 14:30:02.048 3758-3810/com.example.randallsutton.esridemo2 I/OpenGLRenderer: Initialized EGL, version 1.4
03-10 14:30:02.072 3758-3810/com.example.randallsutton.esridemo2 W/EGL_emulation: eglSurfaceAttrib not implemented
03-10 14:30:02.072 3758-3810/com.example.randallsutton.esridemo2 W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdd08e9c0, error=EGL_SUCCESS
03-10 14:30:03.028 3758-3807/com.example.randallsutton.esridemo2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x0000821b
**03-10 14:30:09.348 3758-3803/com.example.randallsutton.esridemo2 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x44 in tid 3803 (Thread-203)**

**Comment by michael-tims** [comment]
At the current Quartz Beta 1 for iOS and Android/Java you would need to wait for the load to complete before adding the symbol to a Graphic and then add the Graphic to the GraphicsOverlay.  For the next Beta release of Quartz this problem has been fixed where the API will load the Picture Marker itself automatically when provided to the API

**Comment by randallsutton** [comment]
That is my question. What is the proper way to wait? Do you have an example?

I noticed if I call loadAsync in my onCreate method it works just fine.

**Comment by dg0yal** [comment]
You need to register a listener on the loadable object (picture marker symbol in this case)
https://developers.arcgis.com/android/beta/api-reference/reference/com/esri/arcgisruntime/loadable/Loadable.html#addDoneLoadingListener(java.lang.Runnable)

**Comment by randallsutton** [comment]
Got it working. Thanks!

```
        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
            // get the point that was clicked and convert it to a point in map coordinates
            final Point point = mMapView.screenToLocation(new android.graphics.Point(Math.round(e.getX()), Math.round(e.getY())));

            // create a marker symbol
            final PictureMarkerSymbol pictureMarkerSymbol = new PictureMarkerSymbol((BitmapDrawable) ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_launcher));
            pictureMarkerSymbol.addDoneLoadingListener(new Runnable() {
                @Override
                public void run() {
                    Graphic graphic = new Graphic(point, pictureMarkerSymbol);

                    // add the graphic to the graphics layer
                    mGraphicsOverlay.getGraphics().add(graphic);
                }
            });
            pictureMarkerSymbol.loadAsync();

            return true;
        }
```
