### ISSUE TITLE
Plans for oauth authentication tokens to be passed in

### ISSUE THREAD

**Issue by ajromanelli** [Esri/runtime-questions#84]
We have a windows app that needs to access arcgis server behind an oauth gateway. There doesn't seem to be a way to pass my previously authenticated token to the runtime so that it can pass thru the gateway and get to server. Is there a workaround to allow for this, or a plan for when this will be supported by the runtime?

**Comment by dotMorten** [comment]
Currently not. We are looking at ways for you to inject yourself into the HTTP stack to inject extra headers like an oauth authentication header. In general we support the authentication schemes that are part of the ArcGIS ecosystem.
