### ISSUE TITLE
Underlying component used to send REST requests, WPF, .Net, quartz .Net

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#85]
For sending REST requests to ArcGIS Server...
WPF SDK used WebRequest.
.Net SDK used HttpRequest.
What does Quartz use in .Net to send REST requests to server?

We are using the __.exe.config file to set maxconnection to higher than 2.   If it is using .net for sending it will probably use that.  True?

**Comment by dotMorten** [comment]
.NET SDK uses [System.Net.HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient%28v=vs.118%29.aspx), not HttpRequest.

I'm not entirely sure if the MaxConnection configuration is affecting HttpClient (documentation isn't clear). Are you not finding this to work?
