### ISSUE TITLE
Roadmap for Offline Maps in the .NET SDK ?

### ISSUE THREAD

**Issue by ghost** [Esri/runtime-questions#89]
There is currently support for map packages and tile packs but Quartz appears to add support for supplying offline map data as:

Mobile map packages 
Mosaic dataset converted to mobile map packages
raw raster data

When will this be coming to the .NET SDK?

**Comment by mbranscomb** [comment]
@ghost 
We are targeting late-Q2 2016 for the first Quartz beta release of the ArcGIS Runtime SDK for .NET. This will include support for the new Mobile Map Package (.mmpk) and Vector Tile Package (.vtpk) formats. Support for direct read of raster data is planned for an update after the initial release in late-Q3 2016.

If you're a .NET developer, we have some more really exciting news: we'll soon be releasing a technical preview of the new ArcGIS Runtime SDK for Xamarin. 

Thanks for your question

Cheers

Mike
