### ISSUE TITLE
External GPS

### ISSUE THREAD

**Issue by madmapper** [Esri/runtime-questions#9]
With more and more external high-accuracy GPS Bluetooth gps unit coming to market, any plans to support in the sdk?  Currently adding support in apps piecemeal.

**Comment by dotMorten** [comment]
For .NET Runtime, see demo app here: https://github.com/Esri/arcgis-runtime-demos-dotnet/tree/master/src/ExternalNmeaGPS

**Comment by madmapper** [comment]
Sorry - should have mentioned iOS

**Comment by EuanCameron** [comment]
Support for hi accuracy external GPS devices is not at the level that we can expose it consistently through the runtime SDKs.   We are following advancements in the individual OSs and when there is enough support we will add support.   iOS is one that is currently falling short in capabilities.
