### ISSUE TITLE
Runtime Geodatabase Support

### ISSUE THREAD

**Issue by fallsdownhill** [Esri/runtime-questions#92]
I'm new to Runtime. Does the geodatabase format support:
-Editing
-Add/Delete
-Relationship Classes
-Tables....non-feature class

Also, I'm forced to work offline, what is required to create a geodatabase? Could the runtime app create one while offline?

**Comment by mbranscomb** [comment]
In the 10.2.X release all the functionaity listed above is supported and will continue to be supported in Quartz. In fact it is available in the Beta 2 releases (Q1 thru Q2). Geodatabases can be extracted from a sync-enabled feature service in which case it is fully editable and can be sync'd. Currently in 10.2.X geodatabases generated from the Desktop software can be opened in read-only mode. We are investigating support for editing those geodatabases created by the Desktop software and also considering the ability for you as a developer to be able to create feature tables both in memory and persisted on disk as a geodatabase.
