### ISSUE TITLE
Are standard runtime license codes reusable?

### ISSUE THREAD

**Issue by mdcooper** [Esri/runtime-questions#99]
For example, if a device dies, is lost, replaced, etc. would we need to request a replacement code, buy a new pack of 25, or can we simply reuse the code?

**Comment by eric906** [comment]
In cases like you've mentioned, you can just re-deploy the app with the same Standard code. The only time you'll need a new code is if you develop a brand new app, and that new app is going to be deployed to that replacement device. I hope that makes sense!
